### PR TITLE
Update configure-usage-rights.md

### PR DESCRIPTION
**Pull request by msmigr**
Do Not Foward does not prevent saving attachments in Preview Pane, nor in recent builds, the message UI.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@msmigr : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@cabailey - Do you want to keep the pull request open, or close it if you're incorporating the changes in a PR you will create? Thanks.

**Comment by cabailey** [comment]
@ktoliver  Yes, let's close this one - it's not quite right either (Save As for the message is disabled, it's Save Attachments that are not disabled).  Fixing in my other PR with other changes.

**Comment by cabailey** [comment]
@ktoliver Why have your merged this when I asked you to close it?

**Comment by msmigr** [comment]
Yep! I realized that soon after I submitted the PR , but that's my first, so I didn't know how to easily resubmit. Good catch!

michael.green@microsoft.com

Mike G



________________________________

**Pull request merged**
