### PR TITLE
Removed the term "all" when talking about file types supported by gen…

### PR DESCRIPTION
**Pull request by Esaggese**
…eric protection

Not *all* file types are supported by generic protection. In particular, Access databases, executables and other such formats aren't supported. Added a clarification regarding this scenario.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by batamig** [comment]
thanks @Esaggese - I just want to check back with the PMs before pushing this update. 
You know that this is the page for the classic client, right? The UL client data is here - maybe we need this change there too?

https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types

**Comment by Esaggese** [comment]
You are correct, the page for the unified labeling client needs to be modified in the same way.

Enrique Saggese | Principal Program Manager – Customer Experience | Microsoft 365 Security, Information Protection and Compliance| Microsoft Corporation | Mobile +1 (425) 894 6696

**Comment by batamig** [comment]
hi @Esaggese , I'm just confirming we've updated this page to read "all supported file formats". I think we can close this PR now.

**Pull request closed without merging**
