### PR TITLE
Update the solution in the FAQ to one that's compatible with Unified …

### PR DESCRIPTION
**Pull request by Esaggese**
…Labeling and built-in sensitivity labels

The original solution proposed in the FAQ to support document templates no longer works in the Unified Labeling or the built-in sensitivity labels since the document property used is no longer present. The updated process is more complex but works in all clients.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mlottner Would you review the update to one of your articles? Thanks!

**Comment by batamig** [comment]
Thanks @mlottner  and @ktoliver !

@Esaggese thanks for taking the time to make this suggestion. We're working through all of the Azure Information Protection docs for unified labeling compliance, and your feedback certainly helps. 

I've passed it back to the team to help validate the procedure, and we should have an update for an upcoming publish.

**Comment by ktoliver** [comment]
@mlottner @batamig Shall we close this pull request or leave it open? Thanks.

**Comment by mlottner** [comment]
@ktoliver we are working to confirm the proposed changes with engineering and PM. We can close and hold it, but we need to confirm technical details before it can be edited and a related PR published.

**Comment by ktoliver** [comment]
@mlottner It sounds like it might be useful to have this PR open as a way to track the issue? I'll leave it open. If you want to close it at any time, you can mention me or enter `#please-close`.

**Comment by batamig** [comment]
Let's close this for now - I've opened a backlog item to track the issue, and have the relevant team members tagged.
@Esaggese if you have any additional comments, you can continue to add them here. Thanks again for your feedback!

#please-close

**Pull request closed without merging**
