### PR TITLE
Creating consistency for caps on encrypt only

### PR DESCRIPTION
**Pull request by KCCross**
Also need to confirm the UI has the hyphen.
We don't use the hyphen unless it's an adjective. Unless it shows up that way in the UI. Thanks, Batami.

Samson Chan, the feature PM was asking - even he's confused :P

### CODE REVIEW

**Comment by PRMerger10** [comment]
@KCCross : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KCCross** [comment]
Batami, please review.

**Comment by ktoliver** [comment]
Hi @KCCross - For future pull requests, this content has a private repository where content developers usually work. You should have access to it as a member of the Microsoft Docs organization. 

Thanks.

**Comment by batamig** [comment]
@ktoliver i updated this content together with another PR today. this pr should be closed.
#please-close

**Pull request closed without merging**
