### PR TITLE
Update quick-file-set-get-label-cpp.md

### PR DESCRIPTION
**Pull request by lvkv**
Similar to https://github.com/MicrosoftDocs/Azure-RMSDocs/pull/1412, I have a few updates to the MIP C++ SDK quickstart for [getting and setting a label](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-cpp). The changes I'm proposing are changes that had to be made for the quickstart to compile and function correctly:

* Add `using mip::ProtectionSettings;` directive
* Change `filePathIn` variable to `inputFilePath`
* Dereference `new ProtectionSettings()`

It might also be worth mentioning the existence of `SetCloud`. I had to add the following line:

```C++
engineSettings.SetCloud(mipns::Cloud::Commercial);
```

below the initialization of `engineSettings` to prevent the MIP SDK from defaulting to AD RMS (on-prem) instead of Azure AIP (cloud).

### CODE REVIEW

**Comment by PRMerger4** [comment]
@lvkv : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by batamig** [comment]
Hi @lvkv, thanks for your additional contribution! I'm tagging @tommoser to comment on this change before we can merge it in.

**Comment by lvkv** [comment]
Any feedback or updates? I reference these docs fairly often, so I'm more than happy to work with you all to make sure these code samples compile, run, and adhere to best practices.

**Comment by tommoser** [comment]
Apologies, I missed the notification. I'm good with these changes.

**Comment by PRMerger19** [comment]
@batamig: I'm sorry - only the author of this article, @msmbaldwin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by msmbaldwin** [comment]
#sign-off

**Pull request merged**
