### PR TITLE
Fixed typo (Connnect)

### PR DESCRIPTION
**Pull request by hubalazs**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@hubalazs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@hubalazs - thanks for catching this.

@cabailey - can you take a look? i also note that the link in the changed line (line 76) seems to point to the wrong URL. It currently points to: https://docs.microsoft.com/en-us/powershell/module/aipservice/connect-aipservice?view=azureipps ... which doesn't match the link text. 

Maybe the URL should be: https://docs.microsoft.com/en-us/powershell/module/AADRM/Connect-AadrmService?view=azureipps

**Comment by cabailey** [comment]
@Jak-MS Yes, I'm guessing the typo is how/why we missed updating this when the newer module came out :)  The cmdlet should be "Connect-AipService" (and the link is correct).

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@cabailey - ah makes sense. I've updated the link text. if this looks good, sign off and i'll merge this. thanks.

**Comment by cabailey** [comment]
@Jak-MS  and @hubalazs Thanks for your help in correcting this!
#sign-off

**Pull request merged**
