### PR TITLE
Change on cmdlet names from Super User Group management

### PR DESCRIPTION
**Pull request by luisarnauth**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@luisarnauth : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by cabailey** [comment]
@luisarnauth Hi Luis, thanks for your contribution!  GitHub doesn't make it easy to see changes in a table.  Am I correct in thinking the only change is from "[Get-AadrmSuperUser cmdlet](/powershell/module/aadrm/get-aadrmsuperuser)." to "[Get-AadrmSuperUser](/powershell/module/aadrm/get-aadrmsuperuser) cmdlet." so the change is to put the word cmdlet outside the link for consistency?

**Comment by luisarnauth** [comment]
Hello Carol,
Sorry for the late response. I've changed the reference you mentioned, but also de the cmdlet right after:
From:
...[**Get-AadrmSuperUser cmdlet**]. To see whether a super user group is configured, use the [**Get-AadrmSuperUser**] cmdlet...
To:
...[**Get-AadrmSuperUser**] cmdlet. To see whether a super user group is configured, use the [**Get-AadrmSuperUserGroup**] cmdlet...
The link from the second cmdlet was right.
Thank you!
Luis Arnauth

**Comment by cabailey** [comment]
@luisarnauth Hi Luis, I didn't get notified that you had responded (best to use the "@" notation in the comments) so only just seen your response & see that this PR now has a merge conflict.  Do you want to resolve that so I can review and merge this PR, or just make sure the change gets made?  Sorry about that!

**Comment by PRMerger20** [comment]
@luisarnauth : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@cabailey - I've resolved the merge conflict. If you approve the proposed changes, please add a sign-off comment and we'll merge the PR. Thanks.

**Comment by cabailey** [comment]
#sign-off

**Pull request merged**
