### PR TITLE
Grammar updates for clarity

### PR DESCRIPTION
**Pull request by mjimison**
Small, grammatical updates to the document

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mjimison : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by cabailey** [comment]
@mjimison Hi Matt!  Thanks for helping to improve the quality of our docs.  I'll take a look at this today.

**Comment by cabailey** [comment]
#hold-off  @mjimison Hi Matt - I'll accept all these, except for the ones that break up long sentences.  We're not allowed to have sentences that contain 30 words or more, and these fail our internal validation tests.  So can you please revert them (95, 103, 113, 115). Modern writing guide style allows us to start a sentence with a conjunction. The only other option is to put them in bulleted lists, which doesn't work in this context. Thanks for your help!

**Comment by PRMerger19** [comment]
@mjimison : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by mjimison** [comment]
Thanks, @cabailey! I've made the changes you requested. Cheers!

**Comment by cabailey** [comment]
@mjimison Thanks.  I missed one at the end but I'll sign this off for merging and then fix myself.
#sign-off

**Pull request merged**
