### PR TITLE
Adding information about TLS 1.2

### PR DESCRIPTION
**Pull request by kommie27**
Adding information about TLS 1.2

### CODE REVIEW

**Comment by PRMerger17** [comment]
@kommie27 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by batamig** [comment]
Thanks @kommie27 for sending us this feedback!
I'm going to check back with the team about this one and update this page as needed.

**Review by Dour420 — CHANGES_REQUESTED** [review]
This is not me

**Comment by batamig** [comment]
Hi, @ktoliver we should close this PR, as this doc update would not currently be correct.
@kommie27, please feel free to continue commenting here as needed.
I also recommend that you check our yammer group if you have further questions. See https://www.yammer.com/askipteam/.

#please-close

**Pull request closed without merging**
