### PR TITLE
Update migrate-from-ad-rms-phase1.md

### PR DESCRIPTION
**Pull request by samschan-ms**
EXO has drepecated support iwth AD RMS, so these steps are no longer necessary. We are only keeping this doc as historical reference.

@cabailey / @KCCross can you review or add the appropriate person to review this?

### CODE REVIEW

**Comment by samschan-ms** [comment]
The other option is to just remove the EXO wiht AD RMS section, and leave the Exchnge on-prem with AD RMS there.

**Comment by Jak-MS** [comment]
@batamig 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by samschan-ms** [comment]
I talked to Enrique before, and this section is no longer needed since we have no customers that wiht EXO+ADRMS state.
My intention was to leave it there for historical accuracy and mark it for customers to skip this section. If it gets too complicated or we can't keep this, then we should update this section and remove it.  possibly add note stating this is no longer a supported configuration for migration.

**Comment by batamig** [comment]
hi @samschan-ms, internal doc updates from Microsoft employees should be made from the private repo.
You can do that by selecting the pencil icon on this page: https://review.learn.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase1 (the "review" at the beginning takes you to the private repo)

Or by using the Learn Editor at https://review.learn.microsoft.com/en-us/admin/?branch=main&editor=load-url
Please also be in touch with @libarson or @aashishr to validate your update as these docs are maintained by the product group.
I'm going to close this now so that you can create the PR from the private repo. Thanks!

#please-close

**Pull request closed without merging**
