### PR TITLE
Update unifiedlabelingclient-version-release-history.md - adding PP note for Network Discovery

### PR DESCRIPTION
**Pull request by HenDaAIP**
@batamig   wanted to add (Public Preview) to all mentions of Network discovery

### CODE REVIEW

**Comment by PRMerger16** [comment]
@HenDaAIP : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @HenDaAIP - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by HenDaAIP** [comment]
Adding @Batami Gold<mailto:Batami.Gold@microsoft.com>.

@Batami<mailto:Batami.Gold@microsoft.com> can you please explain to me tomorrow what I did wrong?

Regards,
Hen.

**Comment by HenDaAIP** [comment]
I see what happened:

Make a small change (for example, fix a typo)
Click the Edit button on a published article; change the repo name by editing the URL. For example, from docs-help to docs-help-pr<https://github.com/MicrosoftDocs/docs-help-pr> or from azure-docs to azure-docs-pr<https://github.com/MicrosoftDocs/azure-docs-pr> and submit fixes. The SpineEdit browser extension<https://github.com/craigshoemaker/spineedit#introduction> can make this process even easier.

We should have changed this URL from
https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/index.yml

to
Azure-RMSDocs-pr/index.yml at master * MicrosoftDocs/Azure-RMSDocs-pr (github.com)<https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/blob/master/Azure-RMSDocs/index.yml>

As you can see I'm pretty new at external contributor guidance ....
See here for more info:
Contributor quick reference - Docs Contributor Guide | Microsoft Docs<https://review.docs.microsoft.com/en-us/help/contribute/contribute-quick-reference?branch=master>

In this case, I made this update<https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#network-discovery-support-public-preview> and other similar ones on other pages in a push we merged earlier today. So I think you can simply close this PR without merging.

Batami

[cid:image001.png@01D6F9A7.3478E080]
Batami Gold
Content Developer
* bagol@microsoft.com<mailto:bagol@microsoft.com>

Need content help?
Add an ADO item for me: Sentinel doc bug<https://mseng.visualstudio.com/TechnicalContent/_workitems/create/Bug?templateId=26938381-a4c4-4db2-a5a1-b4ee6bf11896&ownerId=9b718e24-2d63-471f-9cc8-dd45562f2509> | Sentinel user story<https://mseng.visualstudio.com/TechnicalContent/_workitems/create/User%20Story?templateId=4daa7eb7-76f5-4b98-b1a2-5a070e61dda2&ownerId=9b718e24-2d63-471f-9cc8-dd45562f2509> | AIP backlog<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmseng.visualstudio.com%2FTechnicalContent%2F_workitems%2Fcreate%2FUser%2520Story%3FtemplateId%3D04108be0-4c89-41fd-bf6b-18108073b49c%26ownerId%3D9b718e24-2d63-471f-9cc8-dd45562f2509&data=02%7C01%7CBatami.Gold%40microsoft.com%7C99f3000a250e44f6984408d82edbe95e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637310869346836163&sdata=lXFnNzN5U4GFQr3SMDKDJrK3ahzUOvq%2FIRiqjrrOVi4%3D&reserved=0>
MS ILDC: Time zone PST+10 (Israel) | Work week: Sun - Thurs

From: Hen David <Hen.David@microsoft.com>
Sent: Tuesday, February 2, 2021 8:44 PM
To: MicrosoftDocs/Azure-RMSDocs <reply@reply.github.com>; MicrosoftDocs/Azure-RMSDocs <Azure-RMSDocs@noreply.github.com>; Batami Gold <Batami.Gold@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/Azure-RMSDocs] Update unifiedlabelingclient-version-release-history.md - adding PP note for Network Discovery (#1329)

Adding @Batami Gold<mailto:Batami.Gold@microsoft.com>.

@Batami<mailto:Batami.Gold@microsoft.com> can you please explain to me tomorrow what I did wrong?

Regards,
Hen.

**Pull request closed without merging**
