### PR TITLE
Update requirements-applications.md

### PR DESCRIPTION
**Pull request by Madhan1981**
Hi,

I represent SECUDE. Our solution HALOCAD extends Azure Information Protection (AIP) to protect the following native CAD files.

HALOCAD plugin for AutoCAD: .dwg, .dxf
HALOCAD plugin for Autodesk Inventor: .ipt, .iam, .idw, .ipn
HALOCAD plugin for PTC Creo: asm, prt, mfg, drw, frm, lay, s2d
HALOCAD plugin for Siemens NX: prt, jt

Check out:
https://secude.com/halocad/
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/secudeinternationalag1579872706724.secude_halocad?tab=Overview

Regards,
Madhan

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Madhan1981 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by batamig** [comment]
Hi @Madhan1981 - thanks for getting in touch!
I'm working on adding your plugin, together with the other partner plugin listed, outside the table to differentiate between what's Microsoft supported, and what's partner supported. You should be able to see an update shortly.

I'm closing this PR for now, but feel free to continue commenting as needed. 
We appreciate your contribution!
#please-close

**Comment by Madhan1981** [comment]
Hi @batamig Thanks for the update. We support wide range of different file formats for various native CAD platforms for AIP as mentioned by me on this thread. Let me know if you have any clarifications.

**Comment by Madhan1981** [comment]
Hi @batamig The below are the CAD file formats supported by HALOCAD for AIP. Not sure how to add this.
HALOCAD plugin for AutoCAD: .dwg, .dxf
HALOCAD plugin for Autodesk Inventor: .ipt, .iam, .idw, .ipn
HALOCAD plugin for PTC Creo: asm, .prt, .mfg, .drw, .frm, .lay, .s2d
HALOCAD plugin for Siemens  NX: .prt, .jt
HALOCAD plugin for Solid Edge: .par, .psm, .asm, .dft

**Comment by batamig** [comment]
Thanks @Madhan1981! I'd prefer to link out to a page where you list these for your service, in case it ever changes. Is there a specific URL we should link to where you list the supported file formats?

**Comment by Madhan1981** [comment]
@batamig Thanks. You can link all the supported file formats to https://secude.com/halocad. You can see all the supported file formats in the bottom of the HALOCAD page in FAQ section. Here is the updated file formats supported for different CAD platforms.

HALOCAD plugin for AutoCAD: .dwg, .dxf
HALOCAD plugin for Autodesk Inventor: .ipt, .iam, .idw, .ipn
HALOCAD plugin for RIVET: .rvt, .rfa
HALOCAD plugin for PTC Creo: .asm, .prt, .mfg, .drw, .frm, .lay, .sec
HALOCAD plugin for Siemens NX: .prt
HALOCAD plugin for Solid Edge: .par, .psm, .asm, .dft
HALOCAD plugin for Solid Works: .sldprt, .sldasm, .slddrw, .slddrt
HALOCAD plugin for MicroStation: .dgn

**Pull request closed without merging**
