### PR TITLE
Libarson/scanner update

### PR DESCRIPTION
**Pull request by libarson**

### CODE REVIEW

**Comment by jborsecnik** [comment]
@libarson, if this PR is ready for review and merge, select the "Ready for review" button to move it out of draft mode. Thanks.

**Comment by Jak-MS** [comment]
@rkarlin - assigning to you for review when this is ready.
@batamig - you're the listed author; if this is no longer true can you provide an update to the doc metadata?

- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by batamig** [comment]
Hi @Jak-MS , I'm no longer on this team - I'll check the metadata again to make sure it's assigned correctly. 
Looks like @libarson is managing this update, and it's not meant to go live until October. It should probably be made in the private repo, not this one. @libarson please be in touch offline if you have questions.

**Comment by libarson** [comment]
Hi, I'll be reviewing this with Carol Bailey. We will probably move it to a private repo since it won't be released until public preview on 10/15, sorry for the confusion.

**Pull request closed without merging**
