### PR TITLE
Documenting Office Scripts behavior with Extract/Copy IRM permission

### PR DESCRIPTION
**Pull request by AlexJerabek**
This permission controls the ability of an Office Script to make [external calls](https://learn.microsoft.com/en-us/office/dev/scripts/develop/external-calls) when run in the Excel client.

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Tagging @libarson or @aashishr for approval as per the advice given in https://github.com/MicrosoftDocs/Azure-RMSDocs/pull/1516.

**Comment by American-Dipper** [comment]
@aashishr - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by AlexJerabek** [comment]
Hi @aashishr, 
Any updates?

**Comment by AlexJerabek** [comment]
Pinging again because it's been a month. @American-Dipper @aashishr

**Comment by ShannonLeavitt** [comment]
@batamig - If @aashishr can't review this PR, could you recommend an alternative reviewer?

**Comment by batamig** [comment]
@libarson - can you take a look or re-assign?

**Comment by AlexJerabek** [comment]
@batamig @American-Dipper @aashishr,
This PR has been in limbo for nearly 5 months. What does it take to get this line of text added?

**Comment by Court72** [comment]
I sent an email to the content owner(s) today.

**Comment by aashishr** [comment]
#sign-off

**Pull request merged**
