### PR TITLE
sealpath support pdwg

### PR DESCRIPTION
**Pull request by computeronix**
per sealpath -> https://www.sealpath.com/rmscad/  supports pdwg (see the video on the link and it shows a pdwg file being edited and supported too)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@computeronix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by batamig — COMMENTED** [review]
Hi @computeronix - thanks for this suggestion as well! I need to get this validated by the team before we merge this one in. 
We always appreciate contributions from our users - please feel free to be in touch if you have any questions.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by batamig** [comment]
Hi - coming back to this older PR, according to the team we can't currently add this in our list of official support.
Please let's close this PR.
Thanks!
#please-close

**Pull request closed without merging**
