### PR TITLE
Improve code samples

### PR DESCRIPTION
**Pull request by eNeRGy164**
- Wrap code blocks with language specific tags so code highlighting can work
- Fix smart quotes in code samples
- Aligned some "C++" titles present over code samples
- Don't use I & J in GUID examples, those are not valid Hex chars

### CODE REVIEW

**Comment by PRMerger17** [comment]
@eNeRGy164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @msmbaldwin Could you review this pull request? Thanks.

**Comment by ktoliver** [comment]
@msmbaldwin Could you take a look at this pull request from February? Thanks.

**Comment by ktoliver** [comment]
@rkarlin Could you take a look at this pull request? Thanks.

**Comment by rkarlin** [comment]
@ktoliver this change needs Dev review since it changes the way the code sample runs @mlottner can you please help here?

**Comment by msmbaldwin** [comment]
These look like great improvements. Thank you! #sign-off

**Pull request merged**
