### PR TITLE
Documenting Office Scripts behavior with Extract/Copy IRM permission

### PR DESCRIPTION
**Pull request by AlexJerabek**
This permission controls the ability of an Office Script to make [external calls](https://learn.microsoft.com/en-us/office/dev/scripts/develop/external-calls) when run in the Excel client.

### CODE REVIEW

**Review by gergzk — APPROVED** [review]

**Comment by Court72** [comment]
@batamig

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by batamig** [comment]
Hi Alex, please redirect this PR to the *main* branch of this repo instead of the *master* branch. Azure Information Protection publishes from the *main* branch. Please tag me again when complete and we'll sign off. Thanks!

**Comment by AlexJerabek** [comment]
@batamig, I'm having trouble getting the branches synced because the master branch is still the default when forking or using the Learn edit button.

All I want to actually edit is this table entry in configure-usage-rights.md:
image

And add this line:
In Office Scripts, this allows the script to make outbound network calls.

**Comment by batamig** [comment]
Thanks Alex! That sounds like a bug on the repo - I'm going to look into it with our admins to get it fixed. I appreciate you bringing this to our attention.
In the meantime, I can't approve this content as I'm not actually one of the current content owners. The PM team will need to approve the fix. @libarson, can you help approve this fix and make the change if needed?

**Comment by batamig** [comment]
I also suggest that we close this PR and open a new one with the only change that's needed. It looks like some other changes got pulled into here and I'm not sure that was intentional.

**Pull request closed without merging**
