### PR TITLE
Clarified that the Script method can be applied to Office 2016 and Pro Plus if needed

### PR DESCRIPTION
**Pull request by Esaggese**
Document was worded so it appeared to imply that the DNS record was the only one applicable to Office 2016 and Pro Plus, which is not the case. Since some customers need to use the scripts even on Pro Plus, clarifying that this is supported is important.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Esaggese : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by batamig** [comment]
Thanks @Esaggese . I'm just checking back with the PMs before I push this change through. Thanks again for your feedback!

**Comment by batamig** [comment]
This content was updated in a separate PR. This PR can be closed. Thanks again for the input!
See here for the update https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3

**Comment by msmbaldwin** [comment]
#please-close

**Pull request closed without merging**
