### PR TITLE
Minor grammatical fixes

### PR DESCRIPTION
**Pull request by thechriskent**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@thechriskent : Thanks for your contribution to the Azure documentation! The author, @cabailey, has been notified to review your proposed change.

**Comment by cabailey** [comment]
@thechriskent Thanks for your help again, Chris! Here's my review:

#52: Approve.
#56: Approve.
#67: Approve.
#69: Reject. We are specifically asked to use present tense for localization.
#106: Reject. This comma is needed for localization.
#129: Reject. The path is "C:\Users\Administrator\AppData\Local\Temp" and is not of interest.
#255: Can't see what's changed - is GitHub lying?!

If you revert the rejects, I'll signoff for merging these helpful fixes.

**Comment by cabailey** [comment]
@thechriskent  Ignore the links automatically added in the previous comment!  Refers to line numbers in the file :-)

**Comment by cabailey** [comment]
#hold-off Waiting on the contributor

**Comment by cabailey** [comment]
@thechriskent Thanks for updating.  Nearly there - please change back "your install log path" to "your install log".  It's not the path that's important here, although it's included for completeness.  The main point of the example is showing how the file name is constructed.
#hold-off

**Comment by PRMerger18** [comment]
@thechriskent : Thanks for your contribution to the Azure documentation! The author, @cabailey, has been notified to review your proposed change.

**Comment by cabailey** [comment]
#sign-off 
@thechriskent : Nice fixes & thanks again for your help!

**Pull request merged**
