### PR TITLE
From private repo

### PR DESCRIPTION
**Pull request by Taojunshen**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Taojunshen : Thanks for your contribution! The author, @lleonard-msft, has been notified to review your proposed change.

**Comment by lleonard-msft** [comment]
@BryanLa - I think this is yours now.

**Comment by BryanLa** [comment]
@lleonard-msft - yeah, I'm not sure why these are even generated.. This is for the public/private repo sync, and apparently it's [erroneously] picking up an author from one of the articles pulled in.

**Comment by lleonard-msft** [comment]
@BryanLa - No worries; you might consider updating the metadata in `develop/security-guidelines.md` (as well as any other files that still claim me).

**Comment by BryanLa** [comment]
Sure.. Adding @msmbaldwin as I think he maintains a script that updates metada when authors move around. I believe KV was done, and all of the new MIP stuff is under me, but perhaps some of the AIP articles under Azure-RMSDocs/develop still have your account..

**Pull request merged**
