### PR TITLE
Update plan-implement-tenant-key.md

### PR DESCRIPTION
**Pull request by hobpoblin**
Using BYOK does not provide any additional security over Microsoft-managed keys. I discussed this with Karthik last week and showed him the article and he agreed that it should not contain any words that indicate any difference in the security of one implementation choice or the other.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@hobpoblin : Thanks for your contribution! The author, @cabailey, has been notified to review your proposed change.

**Comment by cabailey** [comment]
@aashishr Please review - I believe you own this messaging.

**Comment by cabailey** [comment]
#hold-off

**Comment by cabailey** [comment]
#sign-off

**Comment by tfosmark** [comment]
@hobpoblin Thank you for this change! I'm merging now.

**Pull request merged**
